import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';


import { AppProvider } from '../context/AppContext';
import CartValue from '../components/CartValue';
import ExpenseList from '../components/ExpenseList';
import ItemSelected from '../components/ItemSelected';
import Location from '../components/Location';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppProvider>
          <div className='container'>
            <h1 className='mt-3'>Shopping App</h1>
            <div className='row mt-3'>
              <div className='col-sm'>
                <CartValue />
              </div>
              <div className='col-sm'>
                <Location />
              </div>
            </div>
            <h3 className='mt-3'>Shopping Cart</h3>
            <div className='row '>
              <div className='col-sm'>
                <ExpenseList />
              </div>
            </div>
            <h3 className='mt-3'>Add Items</h3>
            <div className='row mt-3'>
              <div className='col-sm'>
                <ItemSelected />
              </div>
            </div>
          </div>
        </AppProvider>
      </main>
    </>
  );
}
